name: Pinterest Auto Pin Generator

on:
  schedule:
    - cron: '0 */2 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Packages
        run: npm install

      - name: Run Bot
        run: node index.js
        env:
          PINTEREST_ACCESS_TOKEN: ${{ secrets.PINTEREST_ACCESS_TOKEN }}
          BOARD_ID: ${{ secrets.BOARD_ID }}

      - name: Commit Posted Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/posted.json
          git commit -m "Update Posted Pins" || echo "No changes"
          git push
